import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GraphQL API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  const bodyClassNames = ["min-h-screen", "flex", "flex-col", inter.className].join(" ");

  return (
    <html lang="en">
      <body className={bodyClassNames}>{children}</body>
    </html>
  );
}
