name: Continuous Integration
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  backend:
    name: Golang - Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - uses: arduino/setup-task@v2
      - run: go get ./...
      - run: go build -v ./...
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
    timeout-minutes: 5
  frontend:
    name: Next.js - Build and analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: npm
          cache-dependency-path: app/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run build
    timeout-minutes: 5
